[build]
builder = "DOCKERFILE"
dockerfilePath = "apps/web/Dockerfile"
watchPatterns = [
  "apps/web/**",
  "packages/**",
]

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
numReplicas = 1