/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */
import type { ActivityEventResponseDescription } from "./activityEventResponseDescription";
import type { ActivityEventResponseEmployeeId } from "./activityEventResponseEmployeeId";
import type { ActivityEventResponseEmployeeName } from "./activityEventResponseEmployeeName";
import type { ActivityEventResponsePlatform } from "./activityEventResponsePlatform";
import type { ActivityEventResponseStatus } from "./activityEventResponseStatus";
import type { ActivityEventResponseMetadata } from "./activityEventResponseMetadata";

/**
 * A single unified activity event from any source table.
 */
export interface ActivityEventResponse {
  id: string;
  event_type: string;
  summary: string;
  description?: ActivityEventResponseDescription;
  employee_id?: ActivityEventResponseEmployeeId;
  employee_name?: ActivityEventResponseEmployeeName;
  platform?: ActivityEventResponsePlatform;
  status?: ActivityEventResponseStatus;
  metadata?: ActivityEventResponseMetadata;
  occurred_at: string;
}
