/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */
import type { ActivityEventResponseMetadataAnyOf } from './activityEventResponseMetadataAnyOf';

export type ActivityEventResponseMetadata = ActivityEventResponseMetadataAnyOf | null;
