/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * Today's activity counts grouped by type.
 */
export interface ActivityStatsResponse {
  total_today: number;
  agent_runs: number;
  document_uploads: number;
  employee_events: number;
  tool_usages: number;
  human_escalations: number;
  memory_operations: number;
}
