/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */
import type { ActivityEventResponse } from './activityEventResponse';
import type { ActivityFeedResponseNextOffset } from './activityFeedResponseNextOffset';

/**
 * Paginated activity feed.
 */
export interface ActivityFeedResponse {
  events: ActivityEventResponse[];
  total: number;
  next_offset?: ActivityFeedResponseNextOffset;
}
