/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */
import type { AgentResponseResponse } from "./agentResponseResponse";
import type { FileAttachment } from "./fileAttachment";
import type { AgentResponseError } from "./agentResponseError";

/**
 * Payload returned by the agent after compiling a response.
 */
export interface AgentResponse {
  response: AgentResponseResponse;
  files?: FileAttachment[];
  tool_calls_count: number;
  error?: AgentResponseError;
}
