/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */

export interface ApprovalAssignmentResponse {
  agent_type: string;
  approver_user_id: string;
  id: string;
  org_id: string;
  created_at: string;
  updated_at: string;
}
