/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */
import type { ApprovalRequestResponseEmployeeId } from "./approvalRequestResponseEmployeeId";
import type { ApprovalRequestResponseJobId } from "./approvalRequestResponseJobId";
import type { ApprovalRequestResponseTokenId } from "./approvalRequestResponseTokenId";
import type { ApprovalRequestResponseDelegationId } from "./approvalRequestResponseDelegationId";
import type { ApprovalRequestResponseRedactedParameters } from "./approvalRequestResponseRedactedParameters";
import type { ApprovalRequestResponseRequesterEmail } from "./approvalRequestResponseRequesterEmail";
import type { ApprovalRequestResponseAssignedApproverId } from "./approvalRequestResponseAssignedApproverId";
import type { ApprovalRequestResponseReason } from "./approvalRequestResponseReason";
import type { ApprovalRequestResponseDecision } from "./approvalRequestResponseDecision";
import type { ApprovalRequestResponseExecutionResult } from "./approvalRequestResponseExecutionResult";
import type { ApprovalRequestResponseArmoriqUrl } from "./approvalRequestResponseArmoriqUrl";
import type { ApprovalRequestResponseDecidedAt } from "./approvalRequestResponseDecidedAt";
import type { ApprovalRequestResponseExecutedAt } from "./approvalRequestResponseExecutedAt";

export interface ApprovalRequestResponse {
  id: string;
  org_id: string;
  employee_id: ApprovalRequestResponseEmployeeId;
  job_id: ApprovalRequestResponseJobId;
  plan_hash: string;
  token_id: ApprovalRequestResponseTokenId;
  delegation_id: ApprovalRequestResponseDelegationId;
  mcp: string;
  action: string;
  redacted_parameters: ApprovalRequestResponseRedactedParameters;
  requester_email: ApprovalRequestResponseRequesterEmail;
  assigned_approver_id: ApprovalRequestResponseAssignedApproverId;
  status: string;
  reason: ApprovalRequestResponseReason;
  decision: ApprovalRequestResponseDecision;
  execution_result: ApprovalRequestResponseExecutionResult;
  armoriq_url: ApprovalRequestResponseArmoriqUrl;
  expires_at: string;
  decided_at: ApprovalRequestResponseDecidedAt;
  executed_at: ApprovalRequestResponseExecutedAt;
  created_at: string;
  updated_at: string;
}
