/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */
import type { ApprovalRequestResponse } from "./approvalRequestResponse";

export interface ApprovalListResponse {
  items: ApprovalRequestResponse[];
  total: number;
}
