/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */
import type { ArmorIQMetricsResponseTopAgentsItem } from "./armorIQMetricsResponseTopAgentsItem";
import type { ArmorIQMetricsResponseTopMcpsItem } from "./armorIQMetricsResponseTopMcpsItem";
import type { ArmorIQMetricsResponseTopToolsItem } from "./armorIQMetricsResponseTopToolsItem";
import type { ArmorIQMetricsResponseRecentPlansItem } from "./armorIQMetricsResponseRecentPlansItem";

export interface ArmorIQMetricsResponse {
  status: string;
  total_plans: number;
  total_calls: number;
  allow_count: number;
  hold_count: number;
  block_count: number;
  executed_count: number;
  failed_count: number;
  pending_approvals: number;
  allow_percent: number;
  hold_percent: number;
  block_percent: number;
  top_agents: ArmorIQMetricsResponseTopAgentsItem[];
  top_mcps: ArmorIQMetricsResponseTopMcpsItem[];
  top_tools: ArmorIQMetricsResponseTopToolsItem[];
  recent_plans: ArmorIQMetricsResponseRecentPlansItem[];
  registration_healthy: boolean;
  telemetry_healthy: boolean;
}
