/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */
import type { BodyDocumentsUploadDocumentEmployeeId } from './bodyDocumentsUploadDocumentEmployeeId';

export interface BodyDocumentsUploadDocument {
  file: string;
  organization_id: string;
  employee_id?: BodyDocumentsUploadDocumentEmployeeId;
}
