/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */
import type { CatalogInstallRequestCredential } from './catalogInstallRequestCredential';
import type { CatalogInstallRequestServerUrl } from './catalogInstallRequestServerUrl';

/**
 * Payload for installing a catalog entry as a connection.
 */
export interface CatalogInstallRequest {
  /** API key, PAT, or access token for auth_types that need one */
  credential?: CatalogInstallRequestCredential;
  server_url?: CatalogInstallRequestServerUrl;
  org_wide?: boolean;
}
