/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * API key, PAT, or access token for auth_types that need one
 */
export type CatalogInstallRequestCredential = string | null;
