/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * A marketplace catalog entry (read-only).
 */
export interface CatalogEntryRead {
  slug: string;
  name: string;
  description: string;
  category: string;
  auth_type: string;
  docs_url?: string;
  is_hardcoded?: boolean;
  is_installed?: boolean;
  catalog_state?: string;
  is_installable?: boolean;
  verification_status?: string;
}
