/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */
import type { CreateEmployeeRequestPersonalityAnyOf } from "./createEmployeeRequestPersonalityAnyOf";

export type CreateEmployeeRequestPersonality =
  CreateEmployeeRequestPersonalityAnyOf | null;
