/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */

export interface DocumentsStatsResponse {
  total_files: number;
  total_size_bytes: number;
  org_files_count: number;
  org_size_bytes: number;
  agent_files_count: number;
  agent_size_bytes: number;
  agents_with_files_count: number;
}
