/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */
import type { DocumentResponseEmployeeId } from './documentResponseEmployeeId';
import type { DocumentResponseContentType } from './documentResponseContentType';
import type { DocumentResponseSizeBytes } from './documentResponseSizeBytes';
import type { DocumentResponseEmployeeName } from './documentResponseEmployeeName';

export interface DocumentResponse {
  id: string;
  org_id: string;
  employee_id?: DocumentResponseEmployeeId;
  filename: string;
  content_type?: DocumentResponseContentType;
  size_bytes?: DocumentResponseSizeBytes;
  status: string;
  storage_backend?: string;
  uploaded_at: string;
  employee_name?: DocumentResponseEmployeeName;
}
