/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */
import type { EmployeeResponseEmployeeType } from './employeeResponseEmployeeType';
import type { EmployeeResponseRole } from './employeeResponseRole';
import type { EmployeeResponsePersonality } from './employeeResponsePersonality';
import type { EmployeeResponseSpecialization } from './employeeResponseSpecialization';
import type { EmployeeResponseDuties } from './employeeResponseDuties';
import type { EmployeeResponseMemoryPolicy } from './employeeResponseMemoryPolicy';
import type { EmployeeResponseEscalationPolicy } from './employeeResponseEscalationPolicy';
import type { EmployeeResponseMcpConnections } from './employeeResponseMcpConnections';
import type { EmployeeResponseSlackTeamName } from './employeeResponseSlackTeamName';
import type { EmployeeResponseSlackBotUserId } from './employeeResponseSlackBotUserId';
import type { EmployeeResponseCogneeUserId } from './employeeResponseCogneeUserId';
import type { EmployeeResponseCogneeDatasetName } from './employeeResponseCogneeDatasetName';
import type { ChannelAssignmentResponse } from './channelAssignmentResponse';
import type { EmployeeResponseUpdatedAt } from './employeeResponseUpdatedAt';
import type { EmployeeResponseCurrentTask } from './employeeResponseCurrentTask';
import type { EmployeeResponseLastRunAt } from './employeeResponseLastRunAt';
import type { EmployeeResponseLastError } from './employeeResponseLastError';

export interface EmployeeResponse {
  id: string;
  org_id: string;
  name: string;
  employee_type?: EmployeeResponseEmployeeType;
  role?: EmployeeResponseRole;
  personality?: EmployeeResponsePersonality;
  specialization?: EmployeeResponseSpecialization;
  duties?: EmployeeResponseDuties;
  memory_policy?: EmployeeResponseMemoryPolicy;
  escalation_policy?: EmployeeResponseEscalationPolicy;
  mcp_connections?: EmployeeResponseMcpConnections;
  status: string;
  has_discord_token: boolean;
  has_slack_token: boolean;
  slack_team_name?: EmployeeResponseSlackTeamName;
  slack_bot_user_id?: EmployeeResponseSlackBotUserId;
  cognee_user_id?: EmployeeResponseCogneeUserId;
  cognee_dataset_name?: EmployeeResponseCogneeDatasetName;
  channel_assignments?: ChannelAssignmentResponse[];
  created_at: string;
  updated_at?: EmployeeResponseUpdatedAt;
  operational_status?: string;
  current_task?: EmployeeResponseCurrentTask;
  last_run_at?: EmployeeResponseLastRunAt;
  last_error?: EmployeeResponseLastError;
}
