/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * A file the agent wants to attach to its response (e.g. chart PNG, PDF).

``data`` is base64-encoded so the value is JSON-serializable through
the graph state without a separate blob-storage round-trip.
 */
export interface FileAttachment {
  filename: string;
  /** MIME type such as ``image/png`` or ``application/pdf`` */
  content_type: string;
  /** Base64-encoded file content */
  data: string;
  /** Human-readable label shown in Slack */
  title: string;
}
