/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * Public metadata for a fixed bot (credentials are never exposed).
 */
export interface FixedBotResponse {
  name: string;
  role: string;
  employee_type: string;
  description: string;
  is_configured: boolean;
}
