/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */
import type { McpConnectionCreateAuthType } from './mcpConnectionCreateAuthType';
import type { McpConnectionCreateServerUrl } from './mcpConnectionCreateServerUrl';
import type { McpConnectionCreateScopes } from './mcpConnectionCreateScopes';

/**
 * Payload for creating/updating an API-key or PAT MCP connection.
 */
export interface McpConnectionCreate {
  /** The API key, PAT, or access token to store */
  credential: string;
  /** Optional auth mode to use for this pasted credential (for example pat_bearer) */
  auth_type?: McpConnectionCreateAuthType;
  /** Optional per-connection MCP server URL for connectors that require an org-specific endpoint */
  server_url?: McpConnectionCreateServerUrl;
  scopes?: McpConnectionCreateScopes;
  /** If True, connection is available to all employees in the org */
  org_wide?: boolean;
}
