/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */
import type { McpConnectionRead } from './mcpConnectionRead';

/**
 * Wrapper for listing connections.
 */
export interface McpConnectionList {
  connections: McpConnectionRead[];
}
