/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * Optional auth mode to use for this pasted credential (for example pat_bearer)
 */
export type McpConnectionCreateAuthType = string | null;
