/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * Optional per-connection MCP server URL for connectors that require an org-specific endpoint
 */
export type McpConnectionCreateServerUrl = string | null;
