/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */
import type { McpConnectionReadScopes } from './mcpConnectionReadScopes';
import type { McpConnectionReadLastUsedAt } from './mcpConnectionReadLastUsedAt';

/**
 * Public representation of a stored MCP connection.
 */
export interface McpConnectionRead {
  id: string;
  connector_slug: string;
  auth_type: string;
  scopes?: McpConnectionReadScopes;
  status: string;
  is_org_wide?: boolean;
  last_used_at?: McpConnectionReadLastUsedAt;
  created_at: string;
}
