/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */

export type McpMcpOauthInstallParams = {
/**
 * URL to redirect back to after the OAuth callback
 */
redirect_to?: string | null;
/**
 * Override OAuth client_id (for connectors without hardcoded credentials)
 */
client_id?: string | null;
/**
 * Override OAuth client_secret
 */
client_secret?: string | null;
/**
 * Override OAuth authorize_url (for connectors without hardcoded URLs)
 */
authorize_url?: string | null;
/**
 * Override OAuth token_url
 */
token_url?: string | null;
};
