/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */

export type McpMcpOauthCallbackParams = {
/**
 * Temporary OAuth code from the provider
 */
code: string;
/**
 * State parameter echoed back by the provider
 */
state: string;
/**
 * OAuth error, if the user declined
 */
error?: string | null;
/**
 * Human-readable OAuth error description
 */
error_description?: string | null;
};
