/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * Exact discovered tool name to invoke after tools/list succeeds
 */
export type McpVerificationRequestProbeTool = string | null;
