/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */
import type { McpVerificationRequestProbeTool } from "./mcpVerificationRequestProbeTool";
import type { McpVerificationRequestProbeParameters } from "./mcpVerificationRequestProbeParameters";

/**
 * Verify discovery and optionally run one real read tool through ArmorIQ.
 */
export interface McpVerificationRequest {
  /** Exact discovered tool name to invoke after tools/list succeeds */
  probe_tool?: McpVerificationRequestProbeTool;
  probe_parameters?: McpVerificationRequestProbeParameters;
}
