/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */
import type { MessageInputEmployeeName } from "./messageInputEmployeeName";
import type { MessageInputOrgName } from "./messageInputOrgName";
import type { MessageInputSystemPromptTemplate } from "./messageInputSystemPromptTemplate";

/**
 * Payload representing an incoming message from any gateway or tester.
 */
export interface MessageInput {
  content: string;
  platform: string;
  channel_id: string;
  user_id: string;
  employee_id: string;
  employee_name?: MessageInputEmployeeName;
  org_name?: MessageInputOrgName;
  system_prompt_template?: MessageInputSystemPromptTemplate;
}
