/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */
import type { ScheduleCreateThreadId } from "./scheduleCreateThreadId";

export interface ScheduleCreate {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  /**
   * @minLength 1
   * @maxLength 4000
   */
  prompt: string;
  /**
   * @minLength 9
   * @maxLength 100
   */
  cron_expression: string;
  /** @maxLength 100 */
  timezone?: string;
  /** @pattern ^(slack|discord)$ */
  platform: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  channel_id: string;
  thread_id?: ScheduleCreateThreadId;
}
