/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */
import type { ScheduleResponseThreadId } from './scheduleResponseThreadId';
import type { ScheduleResponseLastRunAt } from './scheduleResponseLastRunAt';
import type { ScheduleResponseLastRunStatus } from './scheduleResponseLastRunStatus';
import type { ScheduleResponseLastError } from './scheduleResponseLastError';
import type { ScheduleResponseUpdatedAt } from './scheduleResponseUpdatedAt';

export interface ScheduleResponse {
  id: string;
  org_id: string;
  employee_id: string;
  name: string;
  prompt: string;
  cron_expression: string;
  timezone: string;
  platform: string;
  channel_id: string;
  thread_id: ScheduleResponseThreadId;
  status: string;
  next_run_at: string;
  last_run_at: ScheduleResponseLastRunAt;
  last_run_status: ScheduleResponseLastRunStatus;
  last_error: ScheduleResponseLastError;
  created_at: string;
  updated_at: ScheduleResponseUpdatedAt;
}
