/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */
import type { ScheduleRunResponseScheduleId } from './scheduleRunResponseScheduleId';
import type { ScheduleRunResponseScheduledFor } from './scheduleRunResponseScheduledFor';
import type { ScheduleRunResponseStartedAt } from './scheduleRunResponseStartedAt';
import type { ScheduleRunResponseFinishedAt } from './scheduleRunResponseFinishedAt';
import type { ScheduleRunResponseResultText } from './scheduleRunResponseResultText';
import type { ScheduleRunResponseError } from './scheduleRunResponseError';
import type { ScheduleRunResponseDeliveryStatus } from './scheduleRunResponseDeliveryStatus';
import type { ScheduleRunResponseDeliveryError } from './scheduleRunResponseDeliveryError';

export interface ScheduleRunResponse {
  id: string;
  schedule_id: ScheduleRunResponseScheduleId;
  status: string;
  scheduled_for: ScheduleRunResponseScheduledFor;
  started_at: ScheduleRunResponseStartedAt;
  finished_at: ScheduleRunResponseFinishedAt;
  result_text: ScheduleRunResponseResultText;
  error: ScheduleRunResponseError;
  attempt: number;
  delivery_status: ScheduleRunResponseDeliveryStatus;
  delivery_error: ScheduleRunResponseDeliveryError;
}
