/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */
import type { ScheduleUpdateName } from './scheduleUpdateName';
import type { ScheduleUpdatePrompt } from './scheduleUpdatePrompt';
import type { ScheduleUpdateCronExpression } from './scheduleUpdateCronExpression';
import type { ScheduleUpdateTimezone } from './scheduleUpdateTimezone';
import type { ScheduleUpdatePlatform } from './scheduleUpdatePlatform';
import type { ScheduleUpdateChannelId } from './scheduleUpdateChannelId';
import type { ScheduleUpdateThreadId } from './scheduleUpdateThreadId';
import type { ScheduleUpdateStatus } from './scheduleUpdateStatus';

export interface ScheduleUpdate {
  name?: ScheduleUpdateName;
  prompt?: ScheduleUpdatePrompt;
  cron_expression?: ScheduleUpdateCronExpression;
  timezone?: ScheduleUpdateTimezone;
  platform?: ScheduleUpdatePlatform;
  channel_id?: ScheduleUpdateChannelId;
  thread_id?: ScheduleUpdateThreadId;
  status?: ScheduleUpdateStatus;
}
