/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */

export type SlackSlackInstallParams = {
/**
 * Employee UUID
 */
employee_id: string;
/**
 * Organization UUID
 */
org_id: string;
/**
 * URL to redirect back to after callback
 */
redirect_to?: string | null;
};
