/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */
import type { UpdateUserRequestName } from './updateUserRequestName';
import type { UpdateUserRequestEmail } from './updateUserRequestEmail';
import type { UpdateUserRequestCurrentPassword } from './updateUserRequestCurrentPassword';
import type { UpdateUserRequestNewPassword } from './updateUserRequestNewPassword';
import type { UpdateUserRequestOnboardingCompleted } from './updateUserRequestOnboardingCompleted';

export interface UpdateUserRequest {
  name?: UpdateUserRequestName;
  email?: UpdateUserRequestEmail;
  current_password?: UpdateUserRequestCurrentPassword;
  new_password?: UpdateUserRequestNewPassword;
  onboarding_completed?: UpdateUserRequestOnboardingCompleted;
}
