/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */
import type { UpdateOrganizationRequestName } from './updateOrganizationRequestName';
import type { UpdateOrganizationRequestDescription } from './updateOrganizationRequestDescription';
import type { UpdateOrganizationRequestWhatItDoes } from './updateOrganizationRequestWhatItDoes';
import type { UpdateOrganizationRequestWebsiteUrl } from './updateOrganizationRequestWebsiteUrl';

export interface UpdateOrganizationRequest {
  name?: UpdateOrganizationRequestName;
  description?: UpdateOrganizationRequestDescription;
  what_it_does?: UpdateOrganizationRequestWhatItDoes;
  website_url?: UpdateOrganizationRequestWebsiteUrl;
}
