/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * One of: legal-compliance, support, hr, general, sales
 */
export type UpdateEmployeeRequestEmployeeType = string | null;
