/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */

export interface UserResponse {
  id: string;
  email: string;
  name: string;
  is_active: boolean;
  onboarding_completed?: boolean;
  created_at: string;
}
