/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  HTTPValidationError,
  ScheduleCreate,
  ScheduleResponse,
  ScheduleRunResponse,
  ScheduleUpdate,
  SchedulesListScheduleRunsRouteParams,
} from "../../schemas";

import { customInstance } from "../../mutator/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Create Schedule Route
 */
export const schedulesCreateScheduleRoute = (
  orgId: string,
  empId: string,
  scheduleCreate: ScheduleCreate,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ScheduleResponse>(
    {
      url: `/api/organizations/${orgId}/employees/${empId}/schedules`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: scheduleCreate,
      signal,
    },
    options,
  );
};

export const getSchedulesCreateScheduleRouteMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof schedulesCreateScheduleRoute>>,
    TError,
    { orgId: string; empId: string; data: ScheduleCreate },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof schedulesCreateScheduleRoute>>,
  TError,
  { orgId: string; empId: string; data: ScheduleCreate },
  TContext
> => {
  const mutationKey = ["schedulesCreateScheduleRoute"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof schedulesCreateScheduleRoute>>,
    { orgId: string; empId: string; data: ScheduleCreate }
  > = (props) => {
    const { orgId, empId, data } = props ?? {};

    return schedulesCreateScheduleRoute(orgId, empId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SchedulesCreateScheduleRouteMutationResult = NonNullable<
  Awaited<ReturnType<typeof schedulesCreateScheduleRoute>>
>;
export type SchedulesCreateScheduleRouteMutationBody = ScheduleCreate;
export type SchedulesCreateScheduleRouteMutationError = HTTPValidationError;

/**
 * @summary Create Schedule Route
 */
export const useSchedulesCreateScheduleRoute = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof schedulesCreateScheduleRoute>>,
      TError,
      { orgId: string; empId: string; data: ScheduleCreate },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof schedulesCreateScheduleRoute>>,
  TError,
  { orgId: string; empId: string; data: ScheduleCreate },
  TContext
> => {
  const mutationOptions =
    getSchedulesCreateScheduleRouteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary List Schedules Route
 */
export const schedulesListSchedulesRoute = (
  orgId: string,
  empId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ScheduleResponse[]>(
    {
      url: `/api/organizations/${orgId}/employees/${empId}/schedules`,
      method: "GET",
      signal,
    },
    options,
  );
};

export const getSchedulesListSchedulesRouteQueryKey = (
  orgId?: string,
  empId?: string,
) => {
  return [`/api/organizations/${orgId}/employees/${empId}/schedules`] as const;
};

export const getSchedulesListSchedulesRouteQueryOptions = <
  TData = Awaited<ReturnType<typeof schedulesListSchedulesRoute>>,
  TError = HTTPValidationError,
>(
  orgId: string,
  empId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof schedulesListSchedulesRoute>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getSchedulesListSchedulesRouteQueryKey(orgId, empId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof schedulesListSchedulesRoute>>
  > = ({ signal }) =>
    schedulesListSchedulesRoute(orgId, empId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(orgId && empId),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof schedulesListSchedulesRoute>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type SchedulesListSchedulesRouteQueryResult = NonNullable<
  Awaited<ReturnType<typeof schedulesListSchedulesRoute>>
>;
export type SchedulesListSchedulesRouteQueryError = HTTPValidationError;

export function useSchedulesListSchedulesRoute<
  TData = Awaited<ReturnType<typeof schedulesListSchedulesRoute>>,
  TError = HTTPValidationError,
>(
  orgId: string,
  empId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof schedulesListSchedulesRoute>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof schedulesListSchedulesRoute>>,
          TError,
          Awaited<ReturnType<typeof schedulesListSchedulesRoute>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useSchedulesListSchedulesRoute<
  TData = Awaited<ReturnType<typeof schedulesListSchedulesRoute>>,
  TError = HTTPValidationError,
>(
  orgId: string,
  empId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof schedulesListSchedulesRoute>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof schedulesListSchedulesRoute>>,
          TError,
          Awaited<ReturnType<typeof schedulesListSchedulesRoute>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useSchedulesListSchedulesRoute<
  TData = Awaited<ReturnType<typeof schedulesListSchedulesRoute>>,
  TError = HTTPValidationError,
>(
  orgId: string,
  empId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof schedulesListSchedulesRoute>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary List Schedules Route
 */

export function useSchedulesListSchedulesRoute<
  TData = Awaited<ReturnType<typeof schedulesListSchedulesRoute>>,
  TError = HTTPValidationError,
>(
  orgId: string,
  empId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof schedulesListSchedulesRoute>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getSchedulesListSchedulesRouteQueryOptions(
    orgId,
    empId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get Schedule Route
 */
export const schedulesGetScheduleRoute = (
  orgId: string,
  empId: string,
  scheduleId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ScheduleResponse>(
    {
      url: `/api/organizations/${orgId}/employees/${empId}/schedules/${scheduleId}`,
      method: "GET",
      signal,
    },
    options,
  );
};

export const getSchedulesGetScheduleRouteQueryKey = (
  orgId?: string,
  empId?: string,
  scheduleId?: string,
) => {
  return [
    `/api/organizations/${orgId}/employees/${empId}/schedules/${scheduleId}`,
  ] as const;
};

export const getSchedulesGetScheduleRouteQueryOptions = <
  TData = Awaited<ReturnType<typeof schedulesGetScheduleRoute>>,
  TError = HTTPValidationError,
>(
  orgId: string,
  empId: string,
  scheduleId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof schedulesGetScheduleRoute>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getSchedulesGetScheduleRouteQueryKey(orgId, empId, scheduleId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof schedulesGetScheduleRoute>>
  > = ({ signal }) =>
    schedulesGetScheduleRoute(orgId, empId, scheduleId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(orgId && empId && scheduleId),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof schedulesGetScheduleRoute>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type SchedulesGetScheduleRouteQueryResult = NonNullable<
  Awaited<ReturnType<typeof schedulesGetScheduleRoute>>
>;
export type SchedulesGetScheduleRouteQueryError = HTTPValidationError;

export function useSchedulesGetScheduleRoute<
  TData = Awaited<ReturnType<typeof schedulesGetScheduleRoute>>,
  TError = HTTPValidationError,
>(
  orgId: string,
  empId: string,
  scheduleId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof schedulesGetScheduleRoute>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof schedulesGetScheduleRoute>>,
          TError,
          Awaited<ReturnType<typeof schedulesGetScheduleRoute>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useSchedulesGetScheduleRoute<
  TData = Awaited<ReturnType<typeof schedulesGetScheduleRoute>>,
  TError = HTTPValidationError,
>(
  orgId: string,
  empId: string,
  scheduleId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof schedulesGetScheduleRoute>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof schedulesGetScheduleRoute>>,
          TError,
          Awaited<ReturnType<typeof schedulesGetScheduleRoute>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useSchedulesGetScheduleRoute<
  TData = Awaited<ReturnType<typeof schedulesGetScheduleRoute>>,
  TError = HTTPValidationError,
>(
  orgId: string,
  empId: string,
  scheduleId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof schedulesGetScheduleRoute>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get Schedule Route
 */

export function useSchedulesGetScheduleRoute<
  TData = Awaited<ReturnType<typeof schedulesGetScheduleRoute>>,
  TError = HTTPValidationError,
>(
  orgId: string,
  empId: string,
  scheduleId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof schedulesGetScheduleRoute>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getSchedulesGetScheduleRouteQueryOptions(
    orgId,
    empId,
    scheduleId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update Schedule Route
 */
export const schedulesUpdateScheduleRoute = (
  orgId: string,
  empId: string,
  scheduleId: string,
  scheduleUpdate: ScheduleUpdate,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<ScheduleResponse>(
    {
      url: `/api/organizations/${orgId}/employees/${empId}/schedules/${scheduleId}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: scheduleUpdate,
    },
    options,
  );
};

export const getSchedulesUpdateScheduleRouteMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof schedulesUpdateScheduleRoute>>,
    TError,
    { orgId: string; empId: string; scheduleId: string; data: ScheduleUpdate },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof schedulesUpdateScheduleRoute>>,
  TError,
  { orgId: string; empId: string; scheduleId: string; data: ScheduleUpdate },
  TContext
> => {
  const mutationKey = ["schedulesUpdateScheduleRoute"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof schedulesUpdateScheduleRoute>>,
    { orgId: string; empId: string; scheduleId: string; data: ScheduleUpdate }
  > = (props) => {
    const { orgId, empId, scheduleId, data } = props ?? {};

    return schedulesUpdateScheduleRoute(
      orgId,
      empId,
      scheduleId,
      data,
      requestOptions,
    );
  };

  return { mutationFn, ...mutationOptions };
};

export type SchedulesUpdateScheduleRouteMutationResult = NonNullable<
  Awaited<ReturnType<typeof schedulesUpdateScheduleRoute>>
>;
export type SchedulesUpdateScheduleRouteMutationBody = ScheduleUpdate;
export type SchedulesUpdateScheduleRouteMutationError = HTTPValidationError;

/**
 * @summary Update Schedule Route
 */
export const useSchedulesUpdateScheduleRoute = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof schedulesUpdateScheduleRoute>>,
      TError,
      {
        orgId: string;
        empId: string;
        scheduleId: string;
        data: ScheduleUpdate;
      },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof schedulesUpdateScheduleRoute>>,
  TError,
  { orgId: string; empId: string; scheduleId: string; data: ScheduleUpdate },
  TContext
> => {
  const mutationOptions =
    getSchedulesUpdateScheduleRouteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Delete Schedule Route
 */
export const schedulesDeleteScheduleRoute = (
  orgId: string,
  empId: string,
  scheduleId: string,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    {
      url: `/api/organizations/${orgId}/employees/${empId}/schedules/${scheduleId}`,
      method: "DELETE",
    },
    options,
  );
};

export const getSchedulesDeleteScheduleRouteMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof schedulesDeleteScheduleRoute>>,
    TError,
    { orgId: string; empId: string; scheduleId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof schedulesDeleteScheduleRoute>>,
  TError,
  { orgId: string; empId: string; scheduleId: string },
  TContext
> => {
  const mutationKey = ["schedulesDeleteScheduleRoute"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof schedulesDeleteScheduleRoute>>,
    { orgId: string; empId: string; scheduleId: string }
  > = (props) => {
    const { orgId, empId, scheduleId } = props ?? {};

    return schedulesDeleteScheduleRoute(
      orgId,
      empId,
      scheduleId,
      requestOptions,
    );
  };

  return { mutationFn, ...mutationOptions };
};

export type SchedulesDeleteScheduleRouteMutationResult = NonNullable<
  Awaited<ReturnType<typeof schedulesDeleteScheduleRoute>>
>;

export type SchedulesDeleteScheduleRouteMutationError = HTTPValidationError;

/**
 * @summary Delete Schedule Route
 */
export const useSchedulesDeleteScheduleRoute = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof schedulesDeleteScheduleRoute>>,
      TError,
      { orgId: string; empId: string; scheduleId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof schedulesDeleteScheduleRoute>>,
  TError,
  { orgId: string; empId: string; scheduleId: string },
  TContext
> => {
  const mutationOptions =
    getSchedulesDeleteScheduleRouteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Run Schedule Route
 */
export const schedulesRunScheduleRoute = (
  orgId: string,
  empId: string,
  scheduleId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ScheduleRunResponse>(
    {
      url: `/api/organizations/${orgId}/employees/${empId}/schedules/${scheduleId}/run`,
      method: "POST",
      signal,
    },
    options,
  );
};

export const getSchedulesRunScheduleRouteMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof schedulesRunScheduleRoute>>,
    TError,
    { orgId: string; empId: string; scheduleId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof schedulesRunScheduleRoute>>,
  TError,
  { orgId: string; empId: string; scheduleId: string },
  TContext
> => {
  const mutationKey = ["schedulesRunScheduleRoute"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof schedulesRunScheduleRoute>>,
    { orgId: string; empId: string; scheduleId: string }
  > = (props) => {
    const { orgId, empId, scheduleId } = props ?? {};

    return schedulesRunScheduleRoute(orgId, empId, scheduleId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SchedulesRunScheduleRouteMutationResult = NonNullable<
  Awaited<ReturnType<typeof schedulesRunScheduleRoute>>
>;

export type SchedulesRunScheduleRouteMutationError = HTTPValidationError;

/**
 * @summary Run Schedule Route
 */
export const useSchedulesRunScheduleRoute = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof schedulesRunScheduleRoute>>,
      TError,
      { orgId: string; empId: string; scheduleId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof schedulesRunScheduleRoute>>,
  TError,
  { orgId: string; empId: string; scheduleId: string },
  TContext
> => {
  const mutationOptions = getSchedulesRunScheduleRouteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary List Schedule Runs Route
 */
export const schedulesListScheduleRunsRoute = (
  orgId: string,
  empId: string,
  scheduleId: string,
  params?: SchedulesListScheduleRunsRouteParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ScheduleRunResponse[]>(
    {
      url: `/api/organizations/${orgId}/employees/${empId}/schedules/${scheduleId}/runs`,
      method: "GET",
      params,
      signal,
    },
    options,
  );
};

export const getSchedulesListScheduleRunsRouteQueryKey = (
  orgId?: string,
  empId?: string,
  scheduleId?: string,
  params?: SchedulesListScheduleRunsRouteParams,
) => {
  return [
    `/api/organizations/${orgId}/employees/${empId}/schedules/${scheduleId}/runs`,
    ...(params ? [params] : []),
  ] as const;
};

export const getSchedulesListScheduleRunsRouteQueryOptions = <
  TData = Awaited<ReturnType<typeof schedulesListScheduleRunsRoute>>,
  TError = HTTPValidationError,
>(
  orgId: string,
  empId: string,
  scheduleId: string,
  params?: SchedulesListScheduleRunsRouteParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof schedulesListScheduleRunsRoute>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getSchedulesListScheduleRunsRouteQueryKey(orgId, empId, scheduleId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof schedulesListScheduleRunsRoute>>
  > = ({ signal }) =>
    schedulesListScheduleRunsRoute(
      orgId,
      empId,
      scheduleId,
      params,
      requestOptions,
      signal,
    );

  return {
    queryKey,
    queryFn,
    enabled: !!(orgId && empId && scheduleId),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof schedulesListScheduleRunsRoute>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type SchedulesListScheduleRunsRouteQueryResult = NonNullable<
  Awaited<ReturnType<typeof schedulesListScheduleRunsRoute>>
>;
export type SchedulesListScheduleRunsRouteQueryError = HTTPValidationError;

export function useSchedulesListScheduleRunsRoute<
  TData = Awaited<ReturnType<typeof schedulesListScheduleRunsRoute>>,
  TError = HTTPValidationError,
>(
  orgId: string,
  empId: string,
  scheduleId: string,
  params: undefined | SchedulesListScheduleRunsRouteParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof schedulesListScheduleRunsRoute>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof schedulesListScheduleRunsRoute>>,
          TError,
          Awaited<ReturnType<typeof schedulesListScheduleRunsRoute>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useSchedulesListScheduleRunsRoute<
  TData = Awaited<ReturnType<typeof schedulesListScheduleRunsRoute>>,
  TError = HTTPValidationError,
>(
  orgId: string,
  empId: string,
  scheduleId: string,
  params?: SchedulesListScheduleRunsRouteParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof schedulesListScheduleRunsRoute>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof schedulesListScheduleRunsRoute>>,
          TError,
          Awaited<ReturnType<typeof schedulesListScheduleRunsRoute>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useSchedulesListScheduleRunsRoute<
  TData = Awaited<ReturnType<typeof schedulesListScheduleRunsRoute>>,
  TError = HTTPValidationError,
>(
  orgId: string,
  empId: string,
  scheduleId: string,
  params?: SchedulesListScheduleRunsRouteParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof schedulesListScheduleRunsRoute>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary List Schedule Runs Route
 */

export function useSchedulesListScheduleRunsRoute<
  TData = Awaited<ReturnType<typeof schedulesListScheduleRunsRoute>>,
  TError = HTTPValidationError,
>(
  orgId: string,
  empId: string,
  scheduleId: string,
  params?: SchedulesListScheduleRunsRouteParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof schedulesListScheduleRunsRoute>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getSchedulesListScheduleRunsRouteQueryOptions(
    orgId,
    empId,
    scheduleId,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
