/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ApprovalActionResponse,
  ApprovalAssignmentResponse,
  ApprovalAssignmentsUpdate,
  ApprovalListResponse,
  ApprovalRequestResponse,
  ApprovalsListApprovalsParams,
  HTTPValidationError,
} from "../../schemas";

import { customInstance } from "../../mutator/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary List Approvals
 */
export const approvalsListApprovals = (
  params: ApprovalsListApprovalsParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ApprovalListResponse>(
    { url: `/api/approvals`, method: "GET", params, signal },
    options,
  );
};

export const getApprovalsListApprovalsQueryKey = (
  params?: ApprovalsListApprovalsParams,
) => {
  return [`/api/approvals`, ...(params ? [params] : [])] as const;
};

export const getApprovalsListApprovalsQueryOptions = <
  TData = Awaited<ReturnType<typeof approvalsListApprovals>>,
  TError = HTTPValidationError,
>(
  params: ApprovalsListApprovalsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof approvalsListApprovals>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getApprovalsListApprovalsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof approvalsListApprovals>>
  > = ({ signal }) => approvalsListApprovals(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof approvalsListApprovals>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type ApprovalsListApprovalsQueryResult = NonNullable<
  Awaited<ReturnType<typeof approvalsListApprovals>>
>;
export type ApprovalsListApprovalsQueryError = HTTPValidationError;

export function useApprovalsListApprovals<
  TData = Awaited<ReturnType<typeof approvalsListApprovals>>,
  TError = HTTPValidationError,
>(
  params: ApprovalsListApprovalsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof approvalsListApprovals>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof approvalsListApprovals>>,
          TError,
          Awaited<ReturnType<typeof approvalsListApprovals>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useApprovalsListApprovals<
  TData = Awaited<ReturnType<typeof approvalsListApprovals>>,
  TError = HTTPValidationError,
>(
  params: ApprovalsListApprovalsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof approvalsListApprovals>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof approvalsListApprovals>>,
          TError,
          Awaited<ReturnType<typeof approvalsListApprovals>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useApprovalsListApprovals<
  TData = Awaited<ReturnType<typeof approvalsListApprovals>>,
  TError = HTTPValidationError,
>(
  params: ApprovalsListApprovalsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof approvalsListApprovals>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary List Approvals
 */

export function useApprovalsListApprovals<
  TData = Awaited<ReturnType<typeof approvalsListApprovals>>,
  TError = HTTPValidationError,
>(
  params: ApprovalsListApprovalsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof approvalsListApprovals>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getApprovalsListApprovalsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get Approval
 */
export const approvalsGetApproval = (
  approvalId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ApprovalRequestResponse>(
    { url: `/api/approvals/${approvalId}`, method: "GET", signal },
    options,
  );
};

export const getApprovalsGetApprovalQueryKey = (approvalId?: string) => {
  return [`/api/approvals/${approvalId}`] as const;
};

export const getApprovalsGetApprovalQueryOptions = <
  TData = Awaited<ReturnType<typeof approvalsGetApproval>>,
  TError = HTTPValidationError,
>(
  approvalId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof approvalsGetApproval>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getApprovalsGetApprovalQueryKey(approvalId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof approvalsGetApproval>>
  > = ({ signal }) => approvalsGetApproval(approvalId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!approvalId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof approvalsGetApproval>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type ApprovalsGetApprovalQueryResult = NonNullable<
  Awaited<ReturnType<typeof approvalsGetApproval>>
>;
export type ApprovalsGetApprovalQueryError = HTTPValidationError;

export function useApprovalsGetApproval<
  TData = Awaited<ReturnType<typeof approvalsGetApproval>>,
  TError = HTTPValidationError,
>(
  approvalId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof approvalsGetApproval>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof approvalsGetApproval>>,
          TError,
          Awaited<ReturnType<typeof approvalsGetApproval>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useApprovalsGetApproval<
  TData = Awaited<ReturnType<typeof approvalsGetApproval>>,
  TError = HTTPValidationError,
>(
  approvalId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof approvalsGetApproval>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof approvalsGetApproval>>,
          TError,
          Awaited<ReturnType<typeof approvalsGetApproval>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useApprovalsGetApproval<
  TData = Awaited<ReturnType<typeof approvalsGetApproval>>,
  TError = HTTPValidationError,
>(
  approvalId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof approvalsGetApproval>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get Approval
 */

export function useApprovalsGetApproval<
  TData = Awaited<ReturnType<typeof approvalsGetApproval>>,
  TError = HTTPValidationError,
>(
  approvalId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof approvalsGetApproval>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getApprovalsGetApprovalQueryOptions(approvalId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Approve Request
 */
export const approvalsApproveRequest = (
  approvalId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ApprovalActionResponse>(
    { url: `/api/approvals/${approvalId}/approve`, method: "POST", signal },
    options,
  );
};

export const getApprovalsApproveRequestMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof approvalsApproveRequest>>,
    TError,
    { approvalId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof approvalsApproveRequest>>,
  TError,
  { approvalId: string },
  TContext
> => {
  const mutationKey = ["approvalsApproveRequest"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof approvalsApproveRequest>>,
    { approvalId: string }
  > = (props) => {
    const { approvalId } = props ?? {};

    return approvalsApproveRequest(approvalId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ApprovalsApproveRequestMutationResult = NonNullable<
  Awaited<ReturnType<typeof approvalsApproveRequest>>
>;

export type ApprovalsApproveRequestMutationError = HTTPValidationError;

/**
 * @summary Approve Request
 */
export const useApprovalsApproveRequest = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof approvalsApproveRequest>>,
      TError,
      { approvalId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof approvalsApproveRequest>>,
  TError,
  { approvalId: string },
  TContext
> => {
  const mutationOptions = getApprovalsApproveRequestMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Reject Request
 */
export const approvalsRejectRequest = (
  approvalId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ApprovalActionResponse>(
    { url: `/api/approvals/${approvalId}/reject`, method: "POST", signal },
    options,
  );
};

export const getApprovalsRejectRequestMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof approvalsRejectRequest>>,
    TError,
    { approvalId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof approvalsRejectRequest>>,
  TError,
  { approvalId: string },
  TContext
> => {
  const mutationKey = ["approvalsRejectRequest"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof approvalsRejectRequest>>,
    { approvalId: string }
  > = (props) => {
    const { approvalId } = props ?? {};

    return approvalsRejectRequest(approvalId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ApprovalsRejectRequestMutationResult = NonNullable<
  Awaited<ReturnType<typeof approvalsRejectRequest>>
>;

export type ApprovalsRejectRequestMutationError = HTTPValidationError;

/**
 * @summary Reject Request
 */
export const useApprovalsRejectRequest = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof approvalsRejectRequest>>,
      TError,
      { approvalId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof approvalsRejectRequest>>,
  TError,
  { approvalId: string },
  TContext
> => {
  const mutationOptions = getApprovalsRejectRequestMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary List Approval Assignments
 */
export const approvalsListApprovalAssignments = (
  orgId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ApprovalAssignmentResponse[]>(
    {
      url: `/api/organizations/${orgId}/approval-assignments`,
      method: "GET",
      signal,
    },
    options,
  );
};

export const getApprovalsListApprovalAssignmentsQueryKey = (orgId?: string) => {
  return [`/api/organizations/${orgId}/approval-assignments`] as const;
};

export const getApprovalsListApprovalAssignmentsQueryOptions = <
  TData = Awaited<ReturnType<typeof approvalsListApprovalAssignments>>,
  TError = HTTPValidationError,
>(
  orgId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof approvalsListApprovalAssignments>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getApprovalsListApprovalAssignmentsQueryKey(orgId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof approvalsListApprovalAssignments>>
  > = ({ signal }) =>
    approvalsListApprovalAssignments(orgId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!orgId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof approvalsListApprovalAssignments>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type ApprovalsListApprovalAssignmentsQueryResult = NonNullable<
  Awaited<ReturnType<typeof approvalsListApprovalAssignments>>
>;
export type ApprovalsListApprovalAssignmentsQueryError = HTTPValidationError;

export function useApprovalsListApprovalAssignments<
  TData = Awaited<ReturnType<typeof approvalsListApprovalAssignments>>,
  TError = HTTPValidationError,
>(
  orgId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof approvalsListApprovalAssignments>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof approvalsListApprovalAssignments>>,
          TError,
          Awaited<ReturnType<typeof approvalsListApprovalAssignments>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useApprovalsListApprovalAssignments<
  TData = Awaited<ReturnType<typeof approvalsListApprovalAssignments>>,
  TError = HTTPValidationError,
>(
  orgId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof approvalsListApprovalAssignments>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof approvalsListApprovalAssignments>>,
          TError,
          Awaited<ReturnType<typeof approvalsListApprovalAssignments>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useApprovalsListApprovalAssignments<
  TData = Awaited<ReturnType<typeof approvalsListApprovalAssignments>>,
  TError = HTTPValidationError,
>(
  orgId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof approvalsListApprovalAssignments>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary List Approval Assignments
 */

export function useApprovalsListApprovalAssignments<
  TData = Awaited<ReturnType<typeof approvalsListApprovalAssignments>>,
  TError = HTTPValidationError,
>(
  orgId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof approvalsListApprovalAssignments>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getApprovalsListApprovalAssignmentsQueryOptions(
    orgId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Replace Approval Assignments
 */
export const approvalsReplaceApprovalAssignments = (
  orgId: string,
  approvalAssignmentsUpdate: ApprovalAssignmentsUpdate,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<ApprovalAssignmentResponse[]>(
    {
      url: `/api/organizations/${orgId}/approval-assignments`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: approvalAssignmentsUpdate,
    },
    options,
  );
};

export const getApprovalsReplaceApprovalAssignmentsMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof approvalsReplaceApprovalAssignments>>,
    TError,
    { orgId: string; data: ApprovalAssignmentsUpdate },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof approvalsReplaceApprovalAssignments>>,
  TError,
  { orgId: string; data: ApprovalAssignmentsUpdate },
  TContext
> => {
  const mutationKey = ["approvalsReplaceApprovalAssignments"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof approvalsReplaceApprovalAssignments>>,
    { orgId: string; data: ApprovalAssignmentsUpdate }
  > = (props) => {
    const { orgId, data } = props ?? {};

    return approvalsReplaceApprovalAssignments(orgId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ApprovalsReplaceApprovalAssignmentsMutationResult = NonNullable<
  Awaited<ReturnType<typeof approvalsReplaceApprovalAssignments>>
>;
export type ApprovalsReplaceApprovalAssignmentsMutationBody =
  ApprovalAssignmentsUpdate;
export type ApprovalsReplaceApprovalAssignmentsMutationError =
  HTTPValidationError;

/**
 * @summary Replace Approval Assignments
 */
export const useApprovalsReplaceApprovalAssignments = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof approvalsReplaceApprovalAssignments>>,
      TError,
      { orgId: string; data: ApprovalAssignmentsUpdate },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof approvalsReplaceApprovalAssignments>>,
  TError,
  { orgId: string; data: ApprovalAssignmentsUpdate },
  TContext
> => {
  const mutationOptions =
    getApprovalsReplaceApprovalAssignmentsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
