/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type {
  HTTPValidationError,
  McpAdaptersZendeskMcp200,
  McpAdaptersZendeskMcpBody,
} from "../../schemas";

import { customInstance } from "../../mutator/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Zendesk Mcp
 */
export const mcpAdaptersZendeskMcp = (
  mcpAdaptersZendeskMcpBody: McpAdaptersZendeskMcpBody,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<McpAdaptersZendeskMcp200>(
    {
      url: `/api/mcp/adapters/zendesk`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: mcpAdaptersZendeskMcpBody,
      signal,
    },
    options,
  );
};

export const getMcpAdaptersZendeskMcpMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof mcpAdaptersZendeskMcp>>,
    TError,
    { data: McpAdaptersZendeskMcpBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof mcpAdaptersZendeskMcp>>,
  TError,
  { data: McpAdaptersZendeskMcpBody },
  TContext
> => {
  const mutationKey = ["mcpAdaptersZendeskMcp"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof mcpAdaptersZendeskMcp>>,
    { data: McpAdaptersZendeskMcpBody }
  > = (props) => {
    const { data } = props ?? {};

    return mcpAdaptersZendeskMcp(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type McpAdaptersZendeskMcpMutationResult = NonNullable<
  Awaited<ReturnType<typeof mcpAdaptersZendeskMcp>>
>;
export type McpAdaptersZendeskMcpMutationBody = McpAdaptersZendeskMcpBody;
export type McpAdaptersZendeskMcpMutationError = HTTPValidationError;

/**
 * @summary Zendesk Mcp
 */
export const useMcpAdaptersZendeskMcp = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof mcpAdaptersZendeskMcp>>,
      TError,
      { data: McpAdaptersZendeskMcpBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof mcpAdaptersZendeskMcp>>,
  TError,
  { data: McpAdaptersZendeskMcpBody },
  TContext
> => {
  const mutationOptions = getMcpAdaptersZendeskMcpMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary N8N Mcp Relay
 */
export const mcpAdaptersN8nMcpRelay = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>(
    { url: `/api/mcp/adapters/n8n`, method: "POST", signal },
    options,
  );
};

export const getMcpAdaptersN8nMcpRelayMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof mcpAdaptersN8nMcpRelay>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof mcpAdaptersN8nMcpRelay>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["mcpAdaptersN8nMcpRelay"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof mcpAdaptersN8nMcpRelay>>,
    void
  > = () => {
    return mcpAdaptersN8nMcpRelay(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type McpAdaptersN8nMcpRelayMutationResult = NonNullable<
  Awaited<ReturnType<typeof mcpAdaptersN8nMcpRelay>>
>;

export type McpAdaptersN8nMcpRelayMutationError = HTTPValidationError;

/**
 * @summary N8N Mcp Relay
 */
export const useMcpAdaptersN8nMcpRelay = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof mcpAdaptersN8nMcpRelay>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof mcpAdaptersN8nMcpRelay>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getMcpAdaptersN8nMcpRelayMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
