/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  HTTPValidationError,
  SlackSlackInstallParams,
  SlackSlackOauthCallbackParams,
} from "../../schemas";

import { customInstance } from "../../mutator/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Redirect the browser to Slack's OAuth authorize page.

The ``employee_id`` and ``org_id`` are baked into a signed state
parameter so the callback can associate the token with the right
employee.

In **fixed** mode the authorize URL uses the fixed bot's client_id
based on the employee's ``employee_type``.
 * @summary Slack Install
 */
export const slackSlackInstall = (
  params: SlackSlackInstallParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>(
    { url: `/api/slack/install`, method: "GET", params, signal },
    options,
  );
};

export const getSlackSlackInstallQueryKey = (
  params?: SlackSlackInstallParams,
) => {
  return [`/api/slack/install`, ...(params ? [params] : [])] as const;
};

export const getSlackSlackInstallQueryOptions = <
  TData = Awaited<ReturnType<typeof slackSlackInstall>>,
  TError = HTTPValidationError,
>(
  params: SlackSlackInstallParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof slackSlackInstall>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSlackSlackInstallQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof slackSlackInstall>>
  > = ({ signal }) => slackSlackInstall(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof slackSlackInstall>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type SlackSlackInstallQueryResult = NonNullable<
  Awaited<ReturnType<typeof slackSlackInstall>>
>;
export type SlackSlackInstallQueryError = HTTPValidationError;

export function useSlackSlackInstall<
  TData = Awaited<ReturnType<typeof slackSlackInstall>>,
  TError = HTTPValidationError,
>(
  params: SlackSlackInstallParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof slackSlackInstall>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof slackSlackInstall>>,
          TError,
          Awaited<ReturnType<typeof slackSlackInstall>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useSlackSlackInstall<
  TData = Awaited<ReturnType<typeof slackSlackInstall>>,
  TError = HTTPValidationError,
>(
  params: SlackSlackInstallParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof slackSlackInstall>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof slackSlackInstall>>,
          TError,
          Awaited<ReturnType<typeof slackSlackInstall>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useSlackSlackInstall<
  TData = Awaited<ReturnType<typeof slackSlackInstall>>,
  TError = HTTPValidationError,
>(
  params: SlackSlackInstallParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof slackSlackInstall>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Slack Install
 */

export function useSlackSlackInstall<
  TData = Awaited<ReturnType<typeof slackSlackInstall>>,
  TError = HTTPValidationError,
>(
  params: SlackSlackInstallParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof slackSlackInstall>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getSlackSlackInstallQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Handle the OAuth redirect from Slack.

1. Validates the state JWT to recover employee / org.
2. Exchanges the ``code`` for a bot token via Slack's API.
3. Encrypts and stores the token on the employee record.
4. Redirects the browser back to the employee's dashboard page.

In **fixed** mode the exchange uses the fixed bot's client secret
based on the employee's ``employee_type``.
 * @summary Slack Oauth Callback
 */
export const slackSlackOauthCallback = (
  params: SlackSlackOauthCallbackParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>(
    { url: `/api/slack/oauth/callback`, method: "GET", params, signal },
    options,
  );
};

export const getSlackSlackOauthCallbackQueryKey = (
  params?: SlackSlackOauthCallbackParams,
) => {
  return [`/api/slack/oauth/callback`, ...(params ? [params] : [])] as const;
};

export const getSlackSlackOauthCallbackQueryOptions = <
  TData = Awaited<ReturnType<typeof slackSlackOauthCallback>>,
  TError = HTTPValidationError,
>(
  params: SlackSlackOauthCallbackParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof slackSlackOauthCallback>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSlackSlackOauthCallbackQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof slackSlackOauthCallback>>
  > = ({ signal }) => slackSlackOauthCallback(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof slackSlackOauthCallback>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type SlackSlackOauthCallbackQueryResult = NonNullable<
  Awaited<ReturnType<typeof slackSlackOauthCallback>>
>;
export type SlackSlackOauthCallbackQueryError = HTTPValidationError;

export function useSlackSlackOauthCallback<
  TData = Awaited<ReturnType<typeof slackSlackOauthCallback>>,
  TError = HTTPValidationError,
>(
  params: SlackSlackOauthCallbackParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof slackSlackOauthCallback>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof slackSlackOauthCallback>>,
          TError,
          Awaited<ReturnType<typeof slackSlackOauthCallback>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useSlackSlackOauthCallback<
  TData = Awaited<ReturnType<typeof slackSlackOauthCallback>>,
  TError = HTTPValidationError,
>(
  params: SlackSlackOauthCallbackParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof slackSlackOauthCallback>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof slackSlackOauthCallback>>,
          TError,
          Awaited<ReturnType<typeof slackSlackOauthCallback>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useSlackSlackOauthCallback<
  TData = Awaited<ReturnType<typeof slackSlackOauthCallback>>,
  TError = HTTPValidationError,
>(
  params: SlackSlackOauthCallbackParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof slackSlackOauthCallback>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Slack Oauth Callback
 */

export function useSlackSlackOauthCallback<
  TData = Awaited<ReturnType<typeof slackSlackOauthCallback>>,
  TError = HTTPValidationError,
>(
  params: SlackSlackOauthCallbackParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof slackSlackOauthCallback>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getSlackSlackOauthCallbackQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
