/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenHuman API
 * OpenHuman — API backend
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ChannelAssignmentResponse,
  CreateChannelAssignmentRequest,
  HTTPValidationError,
} from "../../schemas";

import { customInstance } from "../../mutator/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Create Channel Assignment
 */
export const channelAssignmentsCreateChannelAssignment = (
  orgId: string,
  empId: string,
  createChannelAssignmentRequest: CreateChannelAssignmentRequest,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ChannelAssignmentResponse>(
    {
      url: `/api/organizations/${orgId}/employees/${empId}/channel-assignments`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createChannelAssignmentRequest,
      signal,
    },
    options,
  );
};

export const getChannelAssignmentsCreateChannelAssignmentMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof channelAssignmentsCreateChannelAssignment>>,
    TError,
    { orgId: string; empId: string; data: CreateChannelAssignmentRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof channelAssignmentsCreateChannelAssignment>>,
  TError,
  { orgId: string; empId: string; data: CreateChannelAssignmentRequest },
  TContext
> => {
  const mutationKey = ["channelAssignmentsCreateChannelAssignment"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof channelAssignmentsCreateChannelAssignment>>,
    { orgId: string; empId: string; data: CreateChannelAssignmentRequest }
  > = (props) => {
    const { orgId, empId, data } = props ?? {};

    return channelAssignmentsCreateChannelAssignment(
      orgId,
      empId,
      data,
      requestOptions,
    );
  };

  return { mutationFn, ...mutationOptions };
};

export type ChannelAssignmentsCreateChannelAssignmentMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof channelAssignmentsCreateChannelAssignment>>
  >;
export type ChannelAssignmentsCreateChannelAssignmentMutationBody =
  CreateChannelAssignmentRequest;
export type ChannelAssignmentsCreateChannelAssignmentMutationError =
  HTTPValidationError;

/**
 * @summary Create Channel Assignment
 */
export const useChannelAssignmentsCreateChannelAssignment = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof channelAssignmentsCreateChannelAssignment>>,
      TError,
      { orgId: string; empId: string; data: CreateChannelAssignmentRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof channelAssignmentsCreateChannelAssignment>>,
  TError,
  { orgId: string; empId: string; data: CreateChannelAssignmentRequest },
  TContext
> => {
  const mutationOptions =
    getChannelAssignmentsCreateChannelAssignmentMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary List Channel Assignments
 */
export const channelAssignmentsListChannelAssignments = (
  orgId: string,
  empId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ChannelAssignmentResponse[]>(
    {
      url: `/api/organizations/${orgId}/employees/${empId}/channel-assignments`,
      method: "GET",
      signal,
    },
    options,
  );
};

export const getChannelAssignmentsListChannelAssignmentsQueryKey = (
  orgId?: string,
  empId?: string,
) => {
  return [
    `/api/organizations/${orgId}/employees/${empId}/channel-assignments`,
  ] as const;
};

export const getChannelAssignmentsListChannelAssignmentsQueryOptions = <
  TData = Awaited<ReturnType<typeof channelAssignmentsListChannelAssignments>>,
  TError = HTTPValidationError,
>(
  orgId: string,
  empId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof channelAssignmentsListChannelAssignments>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getChannelAssignmentsListChannelAssignmentsQueryKey(orgId, empId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof channelAssignmentsListChannelAssignments>>
  > = ({ signal }) =>
    channelAssignmentsListChannelAssignments(
      orgId,
      empId,
      requestOptions,
      signal,
    );

  return {
    queryKey,
    queryFn,
    enabled: !!(orgId && empId),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof channelAssignmentsListChannelAssignments>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type ChannelAssignmentsListChannelAssignmentsQueryResult = NonNullable<
  Awaited<ReturnType<typeof channelAssignmentsListChannelAssignments>>
>;
export type ChannelAssignmentsListChannelAssignmentsQueryError =
  HTTPValidationError;

export function useChannelAssignmentsListChannelAssignments<
  TData = Awaited<ReturnType<typeof channelAssignmentsListChannelAssignments>>,
  TError = HTTPValidationError,
>(
  orgId: string,
  empId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof channelAssignmentsListChannelAssignments>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof channelAssignmentsListChannelAssignments>>,
          TError,
          Awaited<ReturnType<typeof channelAssignmentsListChannelAssignments>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useChannelAssignmentsListChannelAssignments<
  TData = Awaited<ReturnType<typeof channelAssignmentsListChannelAssignments>>,
  TError = HTTPValidationError,
>(
  orgId: string,
  empId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof channelAssignmentsListChannelAssignments>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof channelAssignmentsListChannelAssignments>>,
          TError,
          Awaited<ReturnType<typeof channelAssignmentsListChannelAssignments>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useChannelAssignmentsListChannelAssignments<
  TData = Awaited<ReturnType<typeof channelAssignmentsListChannelAssignments>>,
  TError = HTTPValidationError,
>(
  orgId: string,
  empId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof channelAssignmentsListChannelAssignments>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary List Channel Assignments
 */

export function useChannelAssignmentsListChannelAssignments<
  TData = Awaited<ReturnType<typeof channelAssignmentsListChannelAssignments>>,
  TError = HTTPValidationError,
>(
  orgId: string,
  empId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof channelAssignmentsListChannelAssignments>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getChannelAssignmentsListChannelAssignmentsQueryOptions(
    orgId,
    empId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Delete Channel Assignment
 */
export const channelAssignmentsDeleteChannelAssignment = (
  orgId: string,
  empId: string,
  caId: string,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    {
      url: `/api/organizations/${orgId}/employees/${empId}/channel-assignments/${caId}`,
      method: "DELETE",
    },
    options,
  );
};

export const getChannelAssignmentsDeleteChannelAssignmentMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof channelAssignmentsDeleteChannelAssignment>>,
    TError,
    { orgId: string; empId: string; caId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof channelAssignmentsDeleteChannelAssignment>>,
  TError,
  { orgId: string; empId: string; caId: string },
  TContext
> => {
  const mutationKey = ["channelAssignmentsDeleteChannelAssignment"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof channelAssignmentsDeleteChannelAssignment>>,
    { orgId: string; empId: string; caId: string }
  > = (props) => {
    const { orgId, empId, caId } = props ?? {};

    return channelAssignmentsDeleteChannelAssignment(
      orgId,
      empId,
      caId,
      requestOptions,
    );
  };

  return { mutationFn, ...mutationOptions };
};

export type ChannelAssignmentsDeleteChannelAssignmentMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof channelAssignmentsDeleteChannelAssignment>>
  >;

export type ChannelAssignmentsDeleteChannelAssignmentMutationError =
  HTTPValidationError;

/**
 * @summary Delete Channel Assignment
 */
export const useChannelAssignmentsDeleteChannelAssignment = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof channelAssignmentsDeleteChannelAssignment>>,
      TError,
      { orgId: string; empId: string; caId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof channelAssignmentsDeleteChannelAssignment>>,
  TError,
  { orgId: string; empId: string; caId: string },
  TContext
> => {
  const mutationOptions =
    getChannelAssignmentsDeleteChannelAssignmentMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
