"""add_slack_app_slots_and_employee_slack_metadata

Revision ID: 0de87a911e11
Revises: 4c7d2a8e1f3b
Create Date: 2026-07-01 13:19:55.819274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0de87a911e11'
down_revision: Union[str, Sequence[str], None] = '4c7d2a8e1f3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_app_slots',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('slack_app_id', sa.String(length=50), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_secret_enc', sa.Text(), nullable=False),
    sa.Column('app_token_enc', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='available', nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('available', 'assigned', 'disabled')", name='ck_slack_app_slots_status'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.add_column('employees', sa.Column('slack_team_id', sa.String(length=50), nullable=True))
    op.add_column('employees', sa.Column('slack_team_name', sa.String(length=255), nullable=True))
    op.add_column('employees', sa.Column('slack_bot_user_id', sa.String(length=50), nullable=True))
    op.add_column('employees', sa.Column('slack_slot_id', sa.Uuid(), nullable=True))
    op.create_unique_constraint(None, 'employees', ['slack_slot_id'])
    op.create_foreign_key(None, 'employees', 'slack_app_slots', ['slack_slot_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_column('employees', 'slack_slot_id')
    op.drop_column('employees', 'slack_bot_user_id')
    op.drop_column('employees', 'slack_team_name')
    op.drop_column('employees', 'slack_team_id')
    op.drop_table('slack_app_slots')
    # ### end Alembic commands ###
