"""add employee_type column and unique constraint

Revision ID: 522a1ad33217
Revises: f6e28368daa7
Create Date: 2026-07-01 13:23:51.359425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '522a1ad33217'
down_revision: Union[str, Sequence[str], None] = 'f6e28368daa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('employee_type', sa.String(length=50), nullable=True))
    op.create_check_constraint(
        'ck_employees_employee_type',
        'employees',
        "employee_type IS NULL OR employee_type IN ('legal-compliance', 'support', 'hr', 'general')",
    )
    op.create_index('ix_employees_org_id_employee_type', 'employees', ['org_id', 'employee_type'], unique=True, postgresql_where=sa.text('employee_type IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_employees_org_id_employee_type', table_name='employees', postgresql_where=sa.text('employee_type IS NOT NULL'))
    op.drop_constraint('ck_employees_employee_type', 'employees', type_='check')
    op.drop_column('employees', 'employee_type')
    # ### end Alembic commands ###
