"""replace_slot_based_bots_with_fixed_named_bots

Revision ID: a1147141b092
Revises: f442efd78544
Create Date: 2026-07-03 21:14:24.548951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1147141b092'
down_revision: Union[str, Sequence[str], None] = 'f442efd78544'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('employees_slack_slot_id_key'), 'employees', type_='unique')
    op.drop_constraint(op.f('employees_slack_slot_id_fkey'), 'employees', type_='foreignkey')
    op.drop_column('employees', 'slack_slot_id')
    op.drop_table('slack_app_slots')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('slack_slot_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('employees_slack_slot_id_fkey'), 'employees', 'slack_app_slots', ['slack_slot_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint(op.f('employees_slack_slot_id_key'), 'employees', ['slack_slot_id'], postgresql_nulls_not_distinct=False)
    op.create_table('slack_app_slots',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('slack_app_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('client_secret_enc', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('app_token_enc', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'available'::character varying"), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('assigned_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("status::text = ANY (ARRAY['available'::character varying, 'assigned'::character varying, 'disabled'::character varying]::text[])", name=op.f('ck_slack_app_slots_status')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('slack_app_slots_employee_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('slack_app_slots_pkey')),
    sa.UniqueConstraint('employee_id', name=op.f('slack_app_slots_employee_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
