"""add org description and what_it_does

Revision ID: db72d5ea9060
Revises: 3b3f34b263c7
Create Date: 2026-07-01 12:03:25.947902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db72d5ea9060'
down_revision: Union[str, Sequence[str], None] = '3b3f34b263c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('organizations', sa.Column('what_it_does', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'what_it_does')
    op.drop_column('organizations', 'description')
    # ### end Alembic commands ###
