"""add_document_storage_backend

Revision ID: f6e28368daa7
Revises: db72d5ea9060
Create Date: 2026-07-01 12:43:29.184408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6e28368daa7'
down_revision: Union[str, Sequence[str], None] = 'db72d5ea9060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('storage_backend', sa.String(length=20), server_default='local', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'storage_backend')
    # ### end Alembic commands ###
